apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-spring-config
data:
  GREETING: Bonjour
  DATABASE_URI: jdbc:postgresql://postgre:5432/docker-spring
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-spring-secret
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dk
  DATABASE_USER: bXl1c2Vy
