apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-spring
spec:
    replicas: 2
    selector:
       matchLabels:
          app: docker-spring
    template:
       metadata:
          labels:
             app: docker-spring
       spec:
          containers:
          - name: docker-spring
            image: oklimenko/docker-spring:1_0
            env:
              - name: DATABASE_URI
                valueFrom:
                  configMapKeyRef:
                    name: docker-spring-config
                    key: DATABASE_URI

              - name: DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: docker-spring-secret
                    key: DATABASE_USER

              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: docker-spring-secret
                    key: DATABASE_PASSWORD

              - name: GREETING
                valueFrom:
                  configMapKeyRef:
                    name: docker-spring-config
                    key: GREETING
            ports:
              - name: web
                containerPort: 8000
            livenessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 15
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 15
              periodSeconds: 5