apiVersion: v1
kind: Pod
metadata:
  name: docker-spring
  labels:
    app: docker-spring
spec:
  containers:
  - name: docker-spring
    image: oklimenko/docker-spring:1_0
    ports:
      - containerPort: 8000

