apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: docker-spring
spec:
    replicas: 5
    selector:
       matchLabels:
          app: docker-spring
    template:
       metadata:
          labels:
             app: docker-spring
       spec:
          containers:
          - name: docker-spring
            image: oklimenko/docker-spring:1_0
            ports:
              - containerPort: 8000

